name: VitorScallen

on:
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependencies
        run: npm install
      - name: Update README
        run: node update-readme.js
      - name: Commit changes
        run: |
          git config --local user.email "scallen199@gmail.com"
          git config --local user.name "VitorScallen"
          git commit -am "Update README with GitHub stats" || true
          git push
